// This file is automatically generated. Do not edit.
declare namespace PieChartStatisticModuleCssNamespace {
  export interface IPieChartStatisticModuleCss {
    chartWrapper: string;
    legend: string;
    swatch: string;
  }
}

declare const PieChartStatisticModuleCssModule: PieChartStatisticModuleCssNamespace.IPieChartStatisticModuleCss;

export = PieChartStatisticModuleCssModule;
