// This file is automatically generated. Do not edit.
export interface IPieChartStatisticModuleCss {
  chartWrapper: string;
  legend: string;
  swatch: string;
}

export const locals: IPieChartStatisticModuleCss;
export default locals;
