// This file is automatically generated. Do not edit.
declare namespace SimpleStatisticModuleCssNamespace {
  export interface ISimpleStatisticModuleCss {
    gutter: string;
    icon: string;
    simpleStatistic: string;
    title: string;
    titleWrapper: string;
    value: string;
  }
}

declare const SimpleStatisticModuleCssModule: SimpleStatisticModuleCssNamespace.ISimpleStatisticModuleCss;

export = SimpleStatisticModuleCssModule;
