// This file is automatically generated. Do not edit.
export interface ISimpleStatisticModuleCss {
  gutter: string;
  icon: string;
  simpleStatistic: string;
  title: string;
  titleWrapper: string;
  value: string;
}

export const locals: ISimpleStatisticModuleCss;
export default locals;
