// This file is automatically generated. Do not edit.
declare namespace SimpleStatisticModuleCssModule {
  export interface ISimpleStatisticModuleCss {
    gutter: string;
    icon: string;
    simpleStatistic: string;
    title: string;
    titleWrapper: string;
    value: string;
  }
}

declare const SimpleStatisticModuleCssModule: SimpleStatisticModuleCssModule.ISimpleStatisticModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SimpleStatisticModuleCssModule.ISimpleStatisticModuleCss;
};

export = SimpleStatisticModuleCssModule;
