// This file is automatically generated. Do not edit.
declare namespace StatisticsModuleCssNamespace {
  export interface IStatisticsModuleCss {
    gutter: string;
    info: string;
    infoIcon: string;
    lg: string;
    sm: string;
    span1: string;
    span2: string;
    span3: string;
    span4: string;
    statistic: string;
    statistics: string;
    themeBackground: string;
    themeBlue: string;
    xl: string;
  }
}

declare const StatisticsModuleCssModule: StatisticsModuleCssNamespace.IStatisticsModuleCss;

export = StatisticsModuleCssModule;
