// This file is automatically generated. Do not edit.
declare namespace StatisticsModuleCssModule {
  export interface IStatisticsModuleCss {
    gutter: string;
    info: string;
    infoIcon: string;
    lg: string;
    sm: string;
    span1: string;
    span2: string;
    span3: string;
    span4: string;
    statistic: string;
    statistics: string;
    themeBackground: string;
    themeBlue: string;
    xl: string;
  }
}

declare const StatisticsModuleCssModule: StatisticsModuleCssModule.IStatisticsModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StatisticsModuleCssModule.IStatisticsModuleCss;
};

export = StatisticsModuleCssModule;
