// This file is automatically generated. Do not edit.
export const gutter: string;
export const sm: string;
export const lg: string;
export const xl: string;
export const themeBackground: string;
export const themeBlue: string;
export const statistics: string;
export const statistic: string;
export const span1: string;
export const span2: string;
export const span3: string;
export const span4: string;
export const info: string;
export const infoIcon: string;
