// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace TableStatisticModuleCssNamespace {
  export interface ITableStatisticModuleCss {
    container: string;
    table: string;
  }
}

declare const TableStatisticModuleCssModule: TableStatisticModuleCssNamespace.ITableStatisticModuleCss;

export = TableStatisticModuleCssModule;
