// This file is automatically generated. Do not edit.
declare namespace TableModuleCssModule {
  export interface ITableModuleCss {
    block: string;
    celled: string;
    center: string;
    collapsingCell: string;
    collapsingTable: string;
    compact: string;
    errorBackground: string;
    errorText: string;
    left: string;
    negative: string;
    "no-border": string;
    noBorder: string;
    "not-compact": string;
    notCompact: string;
    positive: string;
    right: string;
    successBackground: string;
    successText: string;
    table: string;
    themeBackdrop: string;
    themeBorder: string;
    "very-compact": string;
    veryCompact: string;
    warning: string;
    warningBackground: string;
    warningText: string;
  }
}

declare const TableModuleCssModule: TableModuleCssModule.ITableModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TableModuleCssModule.ITableModuleCss;
};

export = TableModuleCssModule;
