// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ResourceGraphsModuleCssNamespace {
  export interface IResourceGraphsModuleCss {
    graph: string;
    markerContainer: string;
    markerLine: string;
    markerPointerSize: string;
    markerTooltip: string;
    resourceItem: string;
    resourceList: string;
    resourceSwatch: string;
    themeBackground: string;
  }
}

declare const ResourceGraphsModuleCssModule: ResourceGraphsModuleCssNamespace.IResourceGraphsModuleCss;

export = ResourceGraphsModuleCssModule;
