// This file is automatically generated. Do not edit.
export const gutter: string;
export const themeText: string;
export const header: string;
export const resultsContainer: string;
export const reportLink: string;
export const menuLogo: string;
