// This file is automatically generated. Do not edit.
export interface IAnalyseModuleCss {
  header: string;
  resultsContainer: string;
  seeMore: string;
}

export const locals: IAnalyseModuleCss;
export default locals;
