// This file is automatically generated. Do not edit.
declare namespace AnalyseModuleCssModule {
  export interface IAnalyseModuleCss {
    header: string;
    resultsContainer: string;
    seeMore: string;
  }
}

declare const AnalyseModuleCssModule: AnalyseModuleCssModule.IAnalyseModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AnalyseModuleCssModule.IAnalyseModuleCss;
};

export = AnalyseModuleCssModule;
