// This file is automatically generated. Do not edit.
declare namespace SegmentLinkItemModuleCssModule {
  export interface ISegmentLinkItemModuleCss {
    active: string;
    gutter: string;
    link: string;
  }
}

declare const SegmentLinkItemModuleCssModule: SegmentLinkItemModuleCssModule.ISegmentLinkItemModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SegmentLinkItemModuleCssModule.ISegmentLinkItemModuleCss;
};

export = SegmentLinkItemModuleCssModule;
