// This file is automatically generated. Do not edit.
export interface ISegmentLinkItemModuleCss {
  active: string;
  gutter: string;
  link: string;
}

export const locals: ISegmentLinkItemModuleCss;
export default locals;
