import ACTIONS from 'data/ACTIONS'

export const FIRE_SPELLS = [
	ACTIONS.FIRE_I.id,
	ACTIONS.FIRE_II.id,
	ACTIONS.FIRE_III.id,
	ACTIONS.FIRE_IV.id,
	ACTIONS.FLARE.id,
	ACTIONS.DESPAIR.id,
]

export const ICE_SPELLS = [
	ACTIONS.BLIZZARD_I.id,
	ACTIONS.BLIZZARD_II.id,
	ACTIONS.BLIZZARD_III.id,
	ACTIONS.BLIZZARD_IV.id,
	ACTIONS.FREEZE.id,
	ACTIONS.UMBRAL_SOUL.id,
]
