// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace WrapperModuleCssNamespace {
  export interface IWrapperModuleCss {
    link: string;
    procOverlay: string;
  }
}

declare const WrapperModuleCssModule: WrapperModuleCssNamespace.IWrapperModuleCss;

export = WrapperModuleCssModule;
