// This file is automatically generated. Do not edit.
declare namespace WrapperModuleCssModule {
  export interface IWrapperModuleCss {
    link: string;
    procOverlay: string;
  }
}

declare const WrapperModuleCssModule: WrapperModuleCssModule.IWrapperModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: WrapperModuleCssModule.IWrapperModuleCss;
};

export = WrapperModuleCssModule;
