// This file is automatically generated. Do not edit.
declare namespace ItemModuleCssNamespace {
  export interface IItemModuleCss {
    abilityItem: string;
    backgroundColour: string;
    zeroWidthAbility: string;
  }
}

declare const ItemModuleCssModule: ItemModuleCssNamespace.IItemModuleCss;

export = ItemModuleCssModule;
