// This file is automatically generated. Do not edit.
declare namespace ContainerModuleCssModule {
  export interface IContainerModuleCss {
    container: string;
    gutter: string;
    md: string;
  }
}

declare const ContainerModuleCssModule: ContainerModuleCssModule.IContainerModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContainerModuleCssModule.IContainerModuleCss;
};

export = ContainerModuleCssModule;
