// This file is automatically generated. Do not edit.
export interface IContainerModuleCss {
  container: string;
  gutter: string;
  md: string;
}

export const locals: IContainerModuleCss;
export default locals;
