// This file is automatically generated. Do not edit.
declare namespace ContainerModuleCssNamespace {
  export interface IContainerModuleCss {
    container: string;
    gutter: string;
    md: string;
  }
}

declare const ContainerModuleCssModule: ContainerModuleCssNamespace.IContainerModuleCss;

export = ContainerModuleCssModule;
