// This file is automatically generated. Do not edit.
export const gutter: string;
export const md: string;
export const themeText: string;
export const themeBackground: string;
export const crumbs: string;
export const crumbsBackground: string;
export const link: string;
export const linkSubtitle: string;
