// This file is automatically generated. Do not edit.
declare namespace BreadcrumbsModuleCssModule {
  export interface IBreadcrumbsModuleCss {
    crumbs: string;
    crumbsBackground: string;
    gutter: string;
    link: string;
    linkSubtitle: string;
    md: string;
    themeBackground: string;
    themeText: string;
  }
}

declare const BreadcrumbsModuleCssModule: BreadcrumbsModuleCssModule.IBreadcrumbsModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: BreadcrumbsModuleCssModule.IBreadcrumbsModuleCss;
};

export = BreadcrumbsModuleCssModule;
