// This file is automatically generated. Do not edit.
export interface IBreadcrumbsModuleCss {
  crumbs: string;
  crumbsBackground: string;
  gutter: string;
  link: string;
  linkSubtitle: string;
  md: string;
  themeBackground: string;
  themeText: string;
}

export const locals: IBreadcrumbsModuleCss;
export default locals;
