// This file is automatically generated. Do not edit.
declare namespace GlobalSidebarModuleCssNamespace {
  export interface IGlobalSidebarModuleCss {
    center: string;
    content: string;
    gutter: string;
    logo: string;
    logoImage: string;
    md: string;
    options: string;
    sidebar: string;
    themeText: string;
  }
}

declare const GlobalSidebarModuleCssModule: GlobalSidebarModuleCssNamespace.IGlobalSidebarModuleCss;

export = GlobalSidebarModuleCssModule;
