// This file is automatically generated. Do not edit.
export interface IGlobalSidebarModuleCss {
  center: string;
  content: string;
  gutter: string;
  logo: string;
  logoImage: string;
  md: string;
  options: string;
  sidebar: string;
  themeText: string;
}

export const locals: IGlobalSidebarModuleCss;
export default locals;
