// This file is automatically generated. Do not edit.
export const gutter: string;
export const themeText: string;
export const themeBackground: string;
export const sidebar: string;
export const home: string;
export const wrapper: string;
export const logo: string;
export const logoImage: string;
export const content: string;
export const options: string;
