// This file is automatically generated. Do not edit.
declare namespace LegacyBreadcrumbsModuleCssModule {
  export interface ILegacyBreadcrumbsModuleCss {
    crumbs: string;
    crumbsBackground: string;
    gutter: string;
    link: string;
    linkSubtitle: string;
    md: string;
    themeBackground: string;
    themeText: string;
  }
}

declare const LegacyBreadcrumbsModuleCssModule: LegacyBreadcrumbsModuleCssModule.ILegacyBreadcrumbsModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LegacyBreadcrumbsModuleCssModule.ILegacyBreadcrumbsModuleCss;
};

export = LegacyBreadcrumbsModuleCssModule;
