// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace LinksModuleCssNamespace {
  export interface ILinksModuleCss {
    icon: string;
    themeText: string;
  }
}

declare const LinksModuleCssModule: LinksModuleCssNamespace.ILinksModuleCss;

export = LinksModuleCssModule;
