// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace OptionsModuleCssNamespace {
  export interface IOptionsModuleCss {
    gutter: string;
    meta: string;
    row: string;
  }
}

declare const OptionsModuleCssModule: OptionsModuleCssNamespace.IOptionsModuleCss;

export = OptionsModuleCssModule;
