// This file is automatically generated. Do not edit.
export interface IOptionsModuleCss {
  gutter: string;
  horizontal: string;
  icon: string;
  meta: string;
  row: string;
  themeText: string;
  version: string;
  versionInfo: string;
}

export const locals: IOptionsModuleCss;
export default locals;
