// This file is automatically generated. Do not edit.
export interface IReportLinkModuleCss {
  menuLogo: string;
  reportLink: string;
  themeText: string;
}

export const locals: IReportLinkModuleCss;
export default locals;
