// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ReportLinkModuleCssNamespace {
  export interface IReportLinkModuleCss {
    menuLogo: string;
    reportLink: string;
    themeText: string;
  }
}

declare const ReportLinkModuleCssModule: ReportLinkModuleCssNamespace.IReportLinkModuleCss;

export = ReportLinkModuleCssModule;
