// This file is automatically generated. Do not edit.
declare namespace VersionModuleCssNamespace {
  export interface IVersionModuleCss {
    version: string;
    versionInfo: string;
  }
}

declare const VersionModuleCssModule: VersionModuleCssNamespace.IVersionModuleCss;

export = VersionModuleCssModule;
