// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace SuggestionsModuleCssNamespace {
  export interface ISuggestionsModuleCss {
    checkbox: string;
    extra: string;
    gutter: string;
    item: string;
    items: string;
    themeText: string;
    themeTextMuted: string;
  }
}

declare const SuggestionsModuleCssModule: SuggestionsModuleCssNamespace.ISuggestionsModuleCss;

export = SuggestionsModuleCssModule;
