// This file is automatically generated. Do not edit.
declare namespace SuggestionsModuleCssNamespace {
  export interface ISuggestionsModuleCss {
    checkbox: string;
    extra: string;
    gutter: string;
    item: string;
    items: string;
  }
}

declare const SuggestionsModuleCssModule: SuggestionsModuleCssNamespace.ISuggestionsModuleCss;

export = SuggestionsModuleCssModule;
