// This file is automatically generated. Do not edit.
export interface ISuggestionsModuleCss {
  checkbox: string;
  extra: string;
  gutter: string;
  item: string;
  items: string;
}

export const locals: ISuggestionsModuleCss;
export default locals;
