// This file is automatically generated. Do not edit.
declare namespace ComponentModuleCssModule {
  export interface IComponentModuleCss {
    axis: string;
    item: string;
    row: string;
    scaleHandler: string;
    tick: string;
  }
}

declare const ComponentModuleCssModule: ComponentModuleCssModule.IComponentModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ComponentModuleCssModule.IComponentModuleCss;
};

export = ComponentModuleCssModule;
