// This file is automatically generated. Do not edit.
declare namespace BarrageModuleCssNamespace {
  export interface IBarrageModuleCss {
    description: string;
    title: string;
  }
}

declare const BarrageModuleCssModule: BarrageModuleCssNamespace.IBarrageModuleCss;

export = BarrageModuleCssModule;
