// This file is automatically generated. Do not edit.
declare namespace BarrageModuleCssModule {
  export interface IBarrageModuleCss {
    description: string;
    title: string;
  }
}

declare const BarrageModuleCssModule: BarrageModuleCssModule.IBarrageModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: BarrageModuleCssModule.IBarrageModuleCss;
};

export = BarrageModuleCssModule;
