// This file is automatically generated. Do not edit.
declare namespace PitchPerfectModuleCssNamespace {
  export interface IPitchPerfectModuleCss {
    description: string;
    title: string;
  }
}

declare const PitchPerfectModuleCssModule: PitchPerfectModuleCssNamespace.IPitchPerfectModuleCss;

export = PitchPerfectModuleCssModule;
