// This file is automatically generated. Do not edit.
export interface IPitchPerfectModuleCss {
  description: string;
  title: string;
}

export const locals: IPitchPerfectModuleCss;
export default locals;
