// This file is automatically generated. Do not edit.
declare namespace PitchPerfectModuleCssModule {
  export interface IPitchPerfectModuleCss {
    description: string;
    title: string;
  }
}

declare const PitchPerfectModuleCssModule: PitchPerfectModuleCssModule.IPitchPerfectModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PitchPerfectModuleCssModule.IPitchPerfectModuleCss;
};

export = PitchPerfectModuleCssModule;
