// This file is automatically generated. Do not edit.
declare namespace SnapshotsModuleCssNamespace {
  export interface ISnapshotsModuleCss {
    name: string;
  }
}

declare const SnapshotsModuleCssModule: SnapshotsModuleCssNamespace.ISnapshotsModuleCss;

export = SnapshotsModuleCssModule;
