// This file is automatically generated. Do not edit.
declare namespace HeaderModuleCssModule {
  export interface IHeaderModuleCss {
    container: string;
    content: string;
    gutter: string;
    header: string;
    md: string;
    subheader: string;
  }
}

declare const HeaderModuleCssModule: HeaderModuleCssModule.IHeaderModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderModuleCssModule.IHeaderModuleCss;
};

export = HeaderModuleCssModule;
