// This file is automatically generated. Do not edit.
declare namespace ChecklistModuleCssNamespace {
  export interface IChecklistModuleCss {
    description: string;
    lg: string;
    percent: string;
    progress: string;
    title: string;
  }
}

declare const ChecklistModuleCssModule: ChecklistModuleCssNamespace.IChecklistModuleCss;

export = ChecklistModuleCssModule;
