// This file is automatically generated. Do not edit.
declare namespace ChecklistModuleCssModule {
  export interface IChecklistModuleCss {
    description: string;
    lg: string;
    percent: string;
    progress: string;
    title: string;
  }
}

declare const ChecklistModuleCssModule: ChecklistModuleCssModule.IChecklistModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChecklistModuleCssModule.IChecklistModuleCss;
};

export = ChecklistModuleCssModule;
