// This file is automatically generated. Do not edit.
export interface IChecklistModuleCss {
  description: string;
  lg: string;
  percent: string;
  progress: string;
  title: string;
}

export const locals: IChecklistModuleCss;
export default locals;
