// This file is automatically generated. Do not edit.
declare namespace DncGaugesModuleCssModule {
  export interface IDncGaugesModuleCss {
    helpText: string;
  }
}

declare const DncGaugesModuleCssModule: DncGaugesModuleCssModule.IDncGaugesModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: DncGaugesModuleCssModule.IDncGaugesModuleCss;
};

export = DncGaugesModuleCssModule;
