// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace DncGaugesModuleCssNamespace {
  export interface IDncGaugesModuleCss {
    helpText: string;
  }
}

declare const DncGaugesModuleCssModule: DncGaugesModuleCssNamespace.IDncGaugesModuleCss;

export = DncGaugesModuleCssModule;
