// This file is automatically generated. Do not edit.
declare namespace AboutModuleCssNamespace {
  export interface IAboutModuleCss {
    container: string;
    contributor: string;
    gutter: string;
    md: string;
    meta: string;
    themeBackground: string;
  }
}

declare const AboutModuleCssModule: AboutModuleCssNamespace.IAboutModuleCss;

export = AboutModuleCssModule;
