// This file is automatically generated. Do not edit.
declare namespace AboutModuleCssNamespace {
  export interface IAboutModuleCss {
    contributor: string;
    meta: string;
  }
}

declare const AboutModuleCssModule: AboutModuleCssNamespace.IAboutModuleCss;

export = AboutModuleCssModule;
