// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace AboutModuleCssNamespace {
  export interface IAboutModuleCss {
    container: string;
    contributor: string;
    description: string;
    gutter: string;
    md: string;
    meta: string;
    themeBackground: string;
    themeText: string;
  }
}

declare const AboutModuleCssModule: AboutModuleCssNamespace.IAboutModuleCss;

export = AboutModuleCssModule;
