// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace TimelineModuleCssNamespace {
  export interface ITimelineModuleCss {
    expanded: string;
    gutter: string;
    helpText: string;
    timelineWrapper: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssNamespace.ITimelineModuleCss;

export = TimelineModuleCssModule;
