// This file is automatically generated. Do not edit.
export interface ITimelineModuleCss {
  allowOverflow: string;
  gutter: string;
  helpText: string;
}

export const locals: ITimelineModuleCss;
export default locals;
