// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace TimelineModuleCssNamespace {
  export interface ITimelineModuleCss {
    gutter: string;
    helpText: string;
    themeText: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssNamespace.ITimelineModuleCss;

export = TimelineModuleCssModule;
