export default {
	BLOOD_OF_THE_DRAGON_CHECKLIST: 1,
	DISEMBOWEL: 2,
	DEBUFFS: 3,
	DRIFT: 10,
	BLOOD_OF_THE_DRAGON_GAUGE: 11,
	WEAVING: 12,
	BUFFS: 13,
	BATTLE_LITANY: 14,
	TINCTURES: 15,
	POSITIONALS: 16,
}
