// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ActionTimelineModuleCssNamespace {
  export interface IActionTimelineModuleCss {
    backgroundColour: string;
    chargeColor: string;
    chargeGain: string;
    cooldown: string;
    icon: string;
  }
}

declare const ActionTimelineModuleCssModule: ActionTimelineModuleCssNamespace.IActionTimelineModuleCss;

export = ActionTimelineModuleCssModule;
