// This file is automatically generated. Do not edit.
declare namespace ComponentModuleCssModule {
  export interface IComponentModuleCss {
    clickable: string;
    collapsed: string;
    container: string;
    gridLine: string;
    item: string;
    itemContainer: string;
    labelBackground: string;
    labelContent: string;
    row: string;
    scaleHandler: string;
  }
}

declare const ComponentModuleCssModule: ComponentModuleCssModule.IComponentModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ComponentModuleCssModule.IComponentModuleCss;
};

export = ComponentModuleCssModule;
