// This file is automatically generated. Do not edit.
declare namespace TimelineModuleCssModule {
  export interface ITimelineModuleCss {
    axisTick: string;
    borderWidth: string;
    collapsed: string;
    gridLine: string;
    gridLineColour: string;
    interactive: string;
    item: string;
    itemContainer: string;
    labelBackground: string;
    labelContent: string;
    labelSpacer: string;
    minimised: string;
    row: string;
    rowBorderColour: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssModule.ITimelineModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TimelineModuleCssModule.ITimelineModuleCss;
};

export = TimelineModuleCssModule;
