// This file is automatically generated. Do not edit.
declare namespace TimelineModuleCssModule {
  export interface ITimelineModuleCss {
    clickable: string;
    collapsed: string;
    gridLine: string;
    item: string;
    itemContainer: string;
    labelBackground: string;
    labelContent: string;
    row: string;
    scaleHandler: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssModule.ITimelineModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TimelineModuleCssModule.ITimelineModuleCss;
};

export = TimelineModuleCssModule;
