import CoreCooldowns from 'parser/core/modules/Cooldowns'
import ACTIONS from 'data/ACTIONS'

export default class Cooldowns extends CoreCooldowns {
	static cooldownOrder = [
		ACTIONS.ENERGY_DRAIN.id,
		ACTIONS.ENERGY_SIPHON.id,
		ACTIONS.FESTER.id,
		ACTIONS.PAINFLARE.id,
		ACTIONS.BANE.id,
		ACTIONS.DREADWYRM_TRANCE.id,
		ACTIONS.DEATHFLARE.id,
		ACTIONS.SUMMON_BAHAMUT.id,
		ACTIONS.ENKINDLE_BAHAMUT.id,
		ACTIONS.FIREBIRD_TRANCE.id,
		ACTIONS.ENKINDLE_PHOENIX.id,
		ACTIONS.SUMMON.id,
		ACTIONS.EGI_ASSAULT_GARUDA.id,
		ACTIONS.EGI_ASSAULT_II_GARUDA.id,
		ACTIONS.ENKINDLE_GARUDA.id,
		ACTIONS.SUMMON_II.id,
		ACTIONS.EGI_ASSAULT_TITAN.id,
		ACTIONS.EGI_ASSAULT_II_TITAN.id,
		ACTIONS.ENKINDLE_TITAN.id,
		ACTIONS.SUMMON_III.id,
		ACTIONS.EGI_ASSAULT_IFRIT.id,
		ACTIONS.EGI_ASSAULT_II_IFRIT.id,
		ACTIONS.ENKINDLE_IFRIT.id,
		ACTIONS.SMN_AETHERPACT.id,
		ACTIONS.TRI_DISASTER.id,
	]
}
