// This file is automatically generated. Do not edit.
declare namespace TeatimeModuleCssModule {
  export interface ITeatimeModuleCss {
    cdselector: string;
    cduselist: string;
    header: string;
    resultsContainer: string;
    seeMore: string;
  }
}

declare const TeatimeModuleCssModule: TeatimeModuleCssModule.ITeatimeModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TeatimeModuleCssModule.ITeatimeModuleCss;
};

export = TeatimeModuleCssModule;
