import {t} from '@lingui/macro'
import {Trans} from '@lingui/react'
import {ActionLink} from 'components/ui/DbLink'
import {Analyser} from 'parser/core/Analyser'
import {dependency} from 'parser/core/Injectable'
import Checklist, {TieredRule, TARGET, Requirement} from 'parser/core/modules/Checklist'
import {Data} from 'parser/core/modules/Data'
import React from 'react'

// Yes they're the same now, but who knows what the future may bring?
const MAX_STACKS = 3
const STACKS_GAINED = 3

// In seconds
const USE_SEVERITY = {
	95: TARGET.WARN,
	100: TARGET.SUCCESS,
}

export default class Atonement extends Analyser {
	static override handle = 'Atonement'
	static override title = t('pld.Atonement.title')`Atonement`

	@dependency private checklist!: Checklist
	@dependency private data!: Data

	protected stacksUsed: number = 0
	protected potentialStacks: number = 0
	protected currentStacks: number = 0
	protected overcap: number = 0

	override initialise() {

		this.addEventHook({
			type: 'action',
			source: this.parser.actor.id,
			action: this.data.actions.ATONEMENT.id,
		}, () => this.stacksUsed++)

		this.addEventHook({
			type: 'combo',
			source: this.parser.actor.id,
			action: this.data.actions.ROYAL_AUTHORITY.id,
		}, this.onGenerateStacks)

		this.addEventHook('complete', this.onComplete)
	}

	private onGenerateStacks(): void {
		// Tracking overcap in case someone wants to do something with it later
		this.overcap += Math.max(this.currentStacks + STACKS_GAINED - MAX_STACKS, 0)
		this.potentialStacks += STACKS_GAINED
		this.currentStacks = Math.min(this.currentStacks + STACKS_GAINED, MAX_STACKS)
	}

	private onComplete() {

		this.checklist.add(new TieredRule({
			name: <Trans id= "pld.atonement.checklist.name"> Use Atonements Generated By Royal Authority </Trans>,
			description: <Trans id="pld.atonement.checklist.description">
				<ActionLink {...this.data.actions.ROYAL_AUTHORITY} /> generates 3 stacks of Sword Oath to use on <ActionLink {...this.data.actions.ATONEMENT} />,
				this is effectively the same as getting 3 <ActionLink {...this.data.actions.ROYAL_AUTHORITY} /> and you should make sure to use all stacks generated.
			</Trans>,
			tiers: USE_SEVERITY,
			requirements: [
				new Requirement({
					name: <Trans id="pld.atonement.checklist.requirement.atonement.name">
						Uses of <ActionLink {...this.data.actions.ATONEMENT} /> out of possible uses
					</Trans>,
					overrideDisplay: `${this.stacksUsed} / ${this.potentialStacks} (${this.getPercent().toFixed(2)}%)`,
					percent: this.getPercent(),
				}),
			],
		}))
	}

	private getPercent() {
		const actual = this.stacksUsed
		const possible = this.potentialStacks
		return ((actual/possible) * 100)
	}

}
