// This file is automatically generated. Do not edit.
export const gutter: string;
export const highlight: string;
export const themeHover: string;
export const block: string;
export const list: string;
export const listItem: string;
