// This file is automatically generated. Do not edit.
export interface IListModuleCss {
  block: string;
  gutter: string;
  highlight: string;
  list: string;
  listItem: string;
  themeHover: string;
}

export const locals: IListModuleCss;
export default locals;
