// This file is automatically generated. Do not edit.
declare namespace ListModuleCssNamespace {
  export interface IListModuleCss {
    block: string;
    gutter: string;
    highlight: string;
    list: string;
    listItem: string;
    themeHover: string;
  }
}

declare const ListModuleCssModule: ListModuleCssNamespace.IListModuleCss;

export = ListModuleCssModule;
