// This file is automatically generated. Do not edit.
declare namespace AnalyseModuleCssNamespace {
  export interface IAnalyseModuleCss {
    header: string;
    resultsContainer: string;
    seeMore: string;
  }
}

declare const AnalyseModuleCssModule: AnalyseModuleCssNamespace.IAnalyseModuleCss;

export = AnalyseModuleCssModule;
