// This file is automatically generated. Do not edit.
declare namespace SegmentLinkItemModuleCssNamespace {
  export interface ISegmentLinkItemModuleCss {
    active: string;
    gutter: string;
    link: string;
  }
}

declare const SegmentLinkItemModuleCssModule: SegmentLinkItemModuleCssNamespace.ISegmentLinkItemModuleCss;

export = SegmentLinkItemModuleCssModule;
