// This file is automatically generated. Do not edit.
declare namespace ButtonModuleCssModule {
  export interface IButtonModuleCss {
    button: string;
    circular: string;
    compact: string;
    icon: string;
    mini: string;
    nowrap: string;
    small: string;
  }
}

declare const ButtonModuleCssModule: ButtonModuleCssModule.IButtonModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonModuleCssModule.IButtonModuleCss;
};

export = ButtonModuleCssModule;
