// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace AnalyseModuleCssNamespace {
  export interface IAnalyseModuleCss {
    expanded: string;
    expandedModuleExpandButton: string;
    expandedSegment: string;
    gutter: string;
    header: string;
    moduleExpandButton: string;
    moduleExpansionFrame: string;
    moduleHeader: string;
    moduleHeaderActions: string;
    moduleHeaderActionsExpandOnly: string;
    moduleSegment: string;
    moduleTitle: string;
    resultsContainer: string;
    seeMore: string;
    themeBackground: string;
    themeInverse: string;
  }
}

declare const AnalyseModuleCssModule: AnalyseModuleCssNamespace.IAnalyseModuleCss;

export = AnalyseModuleCssModule;
