// This file is automatically generated. Do not edit.
declare namespace EventsViewModuleCssNamespace {
  export interface IEventsViewModuleCss {
    description: string;
    odd: string;
    row: string;
    rowHeight: string;
    showData: string;
    themeBackdrop: string;
    timestamp: string;
    type: string;
  }
}

declare const EventsViewModuleCssModule: EventsViewModuleCssNamespace.IEventsViewModuleCss;

export = EventsViewModuleCssModule;
