// This file is automatically generated. Do not edit.
declare namespace SectStatisticModuleCssModule {
  export interface ISectStatisticModuleCss {
    gutter: string;
    icon: string;
    simpleStatistic: string;
    value: string;
    wrapper: string;
  }
}

declare const SectStatisticModuleCssModule: SectStatisticModuleCssModule.ISectStatisticModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SectStatisticModuleCssModule.ISectStatisticModuleCss;
};

export = SectStatisticModuleCssModule;
