// This file is automatically generated. Do not edit.
export const gutter: string;
export const simpleStatistic: string;
export const wrapper: string;
export const icon: string;
export const value: string;
