// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace SectStatisticModuleCssNamespace {
  export interface ISectStatisticModuleCss {
    gutter: string;
    icon: string;
    simpleStatistic: string;
    value: string;
    wrapper: string;
  }
}

declare const SectStatisticModuleCssModule: SectStatisticModuleCssNamespace.ISectStatisticModuleCss;

export = SectStatisticModuleCssModule;
