// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace JobIconModuleCssNamespace {
  export interface IJobIconModuleCss {
    icon: string;
  }
}

declare const JobIconModuleCssModule: JobIconModuleCssNamespace.IJobIconModuleCss;

export = JobIconModuleCssModule;
