// This file is automatically generated. Do not edit.
declare namespace JobIconModuleCssNamespace {
  export interface IJobIconModuleCss {
    icon: string;
  }
}

declare const JobIconModuleCssModule: JobIconModuleCssNamespace.IJobIconModuleCss;

export = JobIconModuleCssModule;
