// This file is automatically generated. Do not edit.
declare namespace JobIconModuleCssModule {
  export interface IJobIconModuleCss {
    icon: string;
  }
}

declare const JobIconModuleCssModule: JobIconModuleCssModule.IJobIconModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: JobIconModuleCssModule.IJobIconModuleCss;
};

export = JobIconModuleCssModule;
