// This file is automatically generated. Do not edit.
declare namespace AccordionModuleCssModule {
  export interface IAccordionModuleCss {
    accordion: string;
    "accordion-content": string;
    "accordion-title": string;
    accordionContent: string;
    accordionTitle: string;
    gutter: string;
    md: string;
    "no-bullet": string;
    noBullet: string;
    themeBorder: string;
  }
}

declare const AccordionModuleCssModule: AccordionModuleCssModule.IAccordionModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AccordionModuleCssModule.IAccordionModuleCss;
};

export = AccordionModuleCssModule;
