// This file is automatically generated. Do not edit.
declare namespace HomeModuleCssModule {
  export interface IHomeModuleCss {
    about: string;
    background: string;
    gutter: string;
    logo: string;
    md: string;
    options: string;
    search: string;
    themeBackground: string;
    themeText: string;
  }
}

declare const HomeModuleCssModule: HomeModuleCssModule.IHomeModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeModuleCssModule.IHomeModuleCss;
};

export = HomeModuleCssModule;
