// This file is automatically generated. Do not edit.
export interface IHomeModuleCss {
  about: string;
  background: string;
  gutter: string;
  logo: string;
  md: string;
  options: string;
  search: string;
  themeBackground: string;
  themeText: string;
}

export const locals: IHomeModuleCss;
export default locals;
