// This file is automatically generated. Do not edit.
export const gutter: string;
export const md: string;
export const themeText: string;
export const themeBackground: string;
export const background: string;
export const logo: string;
export const search: string;
export const about: string;
export const options: string;
