// This file is automatically generated. Do not edit.
declare namespace ReportSearchModuleCssModule {
  export interface IReportSearchModuleCss {
    input: string;
  }
}

declare const ReportSearchModuleCssModule: ReportSearchModuleCssModule.IReportSearchModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ReportSearchModuleCssModule.IReportSearchModuleCss;
};

export = ReportSearchModuleCssModule;
