// This file is automatically generated. Do not edit.
declare namespace ReportSearchModuleCssNamespace {
  export interface IReportSearchModuleCss {
    input: string;
  }
}

declare const ReportSearchModuleCssModule: ReportSearchModuleCssNamespace.IReportSearchModuleCss;

export = ReportSearchModuleCssModule;
