// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ReportSearchModuleCssNamespace {
  export interface IReportSearchModuleCss {
    input: string;
  }
}

declare const ReportSearchModuleCssModule: ReportSearchModuleCssNamespace.IReportSearchModuleCss;

export = ReportSearchModuleCssModule;
