// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace SupportSummaryModuleCssNamespace {
  export interface ISupportSummaryModuleCss {
    errorBackground: string;
    errorText: string;
    header: string;
    job: string;
    jobs: string;
    md: string;
    outdated: string;
    sm: string;
    summary: string;
    supportGrid: string;
    supported: string;
    themeBackground: string;
    themeText: string;
    unknown: string;
    unsupported: string;
    warningBackground: string;
    warningText: string;
  }
}

declare const SupportSummaryModuleCssModule: SupportSummaryModuleCssNamespace.ISupportSummaryModuleCss;

export = SupportSummaryModuleCssModule;
