// This file is automatically generated. Do not edit.
declare namespace ItemModuleCssModule {
  export interface IItemModuleCss {
    abilityItem: string;
    zeroWidthAbility: string;
  }
}

declare const ItemModuleCssModule: ItemModuleCssModule.IItemModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ItemModuleCssModule.IItemModuleCss;
};

export = ItemModuleCssModule;
