// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace HiganbanaModuleCssNamespace {
  export interface IHiganbanaModuleCss {
    name: string;
  }
}

declare const HiganbanaModuleCssModule: HiganbanaModuleCssNamespace.IHiganbanaModuleCss;

export = HiganbanaModuleCssModule;
