// This file is automatically generated. Do not edit.
declare namespace KenkiModuleCssNamespace {
  export interface IKenkiModuleCss {
    helpText: string;
  }
}

declare const KenkiModuleCssModule: KenkiModuleCssNamespace.IKenkiModuleCss;

export = KenkiModuleCssModule;
