// This file is automatically generated. Do not edit.
declare namespace KenkiModuleCssModule {
  export interface IKenkiModuleCss {
    helpText: string;
  }
}

declare const KenkiModuleCssModule: KenkiModuleCssModule.IKenkiModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: KenkiModuleCssModule.IKenkiModuleCss;
};

export = KenkiModuleCssModule;
