// This file is automatically generated. Do not edit.
declare namespace AppModuleCssModule {
  export interface IAppModuleCss {
    container: string;
    content: string;
    gutter: string;
    hamburger: string;
    headerHeight: string;
    home: string;
    lg: string;
    logo: string;
    logoImage: string;
    md: string;
    mobileHeader: string;
    open: string;
    sidebar: string;
    sidebarBackdrop: string;
    sidebarWrapper: string;
    themeBackground: string;
    themeInverse: string;
    themeText: string;
  }
}

declare const AppModuleCssModule: AppModuleCssModule.IAppModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppModuleCssModule.IAppModuleCss;
};

export = AppModuleCssModule;
