// This file is automatically generated. Do not edit.
declare namespace AppModuleCssNamespace {
  export interface IAppModuleCss {
    container: string;
    content: string;
    gutter: string;
    hamburger: string;
    headerHeight: string;
    home: string;
    lg: string;
    logo: string;
    logoImage: string;
    md: string;
    mobileHeader: string;
    open: string;
    sidebar: string;
    sidebarBackdrop: string;
    sidebarWrapper: string;
    themeBackground: string;
    themeInverse: string;
    themeText: string;
  }
}

declare const AppModuleCssModule: AppModuleCssNamespace.IAppModuleCss;

export = AppModuleCssModule;
