// This file is automatically generated. Do not edit.
export const gutter: string;
export const md: string;
export const lg: string;
export const themeBackground: string;
export const mobileHeader: string;
export const container: string;
export const sidebar: string;
export const home: string;
export const content: string;
