// This file is automatically generated. Do not edit.
export const gutter: string;
export const lg: string;
export const themeBackground: string;
export const container: string;
export const text: string;
export const background: string;
