// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace BranchBannerModuleCssNamespace {
  export interface IBranchBannerModuleCss {
    background: string;
    container: string;
    gutter: string;
    lg: string;
    text: string;
    themeBackground: string;
  }
}

declare const BranchBannerModuleCssModule: BranchBannerModuleCssNamespace.IBranchBannerModuleCss;

export = BranchBannerModuleCssModule;
