// This file is automatically generated. Do not edit.
export interface IErrorBoundaryModuleCss {
  refresh: string;
  refreshHeader: string;
}

export const locals: IErrorBoundaryModuleCss;
export default locals;
