// This file is automatically generated. Do not edit.
declare namespace ErrorBoundaryModuleCssModule {
  export interface IErrorBoundaryModuleCss {
    refresh: string;
    refreshHeader: string;
  }
}

declare const ErrorBoundaryModuleCssModule: ErrorBoundaryModuleCssModule.IErrorBoundaryModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ErrorBoundaryModuleCssModule.IErrorBoundaryModuleCss;
};

export = ErrorBoundaryModuleCssModule;
