// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ErrorBoundaryModuleCssNamespace {
  export interface IErrorBoundaryModuleCss {
    refresh: string;
    refreshHeader: string;
  }
}

declare const ErrorBoundaryModuleCssModule: ErrorBoundaryModuleCssNamespace.IErrorBoundaryModuleCss;

export = ErrorBoundaryModuleCssModule;
