// This file is automatically generated. Do not edit.
declare namespace I18NOverlayModuleCssModule {
  export interface II18NOverlayModuleCss {
    error: string;
    "missing-id": string;
    missingId: string;
    "not-translated": string;
    notTranslated: string;
    segment: string;
  }
}

declare const I18NOverlayModuleCssModule: I18NOverlayModuleCssModule.II18NOverlayModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: I18NOverlayModuleCssModule.II18NOverlayModuleCss;
};

export = I18NOverlayModuleCssModule;
