// This file is automatically generated. Do not edit.
declare namespace I18NOverlayModuleCssNamespace {
  export interface II18NOverlayModuleCss {
    error: string;
    "missing-id": string;
    missingId: string;
    "not-translated": string;
    notTranslated: string;
    segment: string;
  }
}

declare const I18NOverlayModuleCssModule: I18NOverlayModuleCssNamespace.II18NOverlayModuleCss;

export = I18NOverlayModuleCssModule;
