// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace I18NLoaderModuleCssNamespace {
  export interface II18NLoaderModuleCss {
    translationMissing: string;
    translationWrapper: string;
  }
}

declare const I18NLoaderModuleCssModule: I18NLoaderModuleCssNamespace.II18NLoaderModuleCss;

export = I18NLoaderModuleCssModule;
