// This file is automatically generated. Do not edit.
export interface II18nOverlayModuleCss {
  error: string;
  "missing-id": string;
  missingId: string;
  "not-translated": string;
  notTranslated: string;
  segment: string;
}

export const locals: II18nOverlayModuleCss;
export default locals;
