// This file is automatically generated. Do not edit.
declare namespace TimelineModuleCssModule {
  export interface ITimelineModuleCss {
    axisTick: string;
    borderWidth: string;
    branchLabelWidth: string;
    collapsed: string;
    defaultRowHeight: string;
    first: string;
    gridLine: string;
    gridLineColour: string;
    hasChildren: string;
    item: string;
    label: string;
    major: string;
    majorGridLineColour: string;
    timeline: string;
    track: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssModule.ITimelineModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TimelineModuleCssModule.ITimelineModuleCss;
};

export = TimelineModuleCssModule;
