// This file is automatically generated. Do not edit.
export interface IArcanaSuggestionsModuleCss {
  buffIcon: string;
  buffPlaceholder: string;
  buffUnknown: string;
  cardActionRow: string;
  cardActionTable: string;
  jobIcon: string;
  sealIcon: string;
  sealIconContainer: string;
}

export const locals: IArcanaSuggestionsModuleCss;
export default locals;
