// This file is automatically generated. Do not edit.
declare namespace ArcanaSuggestionsModuleCssNamespace {
  export interface IArcanaSuggestionsModuleCss {
    buffIcon: string;
    buffPlaceholder: string;
    buffUnknown: string;
    cardActionRow: string;
    cardActionTable: string;
    jobIcon: string;
    sealIcon: string;
    sealIconContainer: string;
  }
}

declare const ArcanaSuggestionsModuleCssModule: ArcanaSuggestionsModuleCssNamespace.IArcanaSuggestionsModuleCss;

export = ArcanaSuggestionsModuleCssModule;
