// This file is automatically generated. Do not edit.
export const jobIcon: string;
export const cardActionRow: string;
export const cardActionTable: string;
export const buffIcon: string;
export const buffPlaceholder: string;
export const buffUnknown: string;
export const sealIconContainer: string;
export const sealIcon: string;
