// This file is automatically generated. Do not edit.
declare namespace ChangeLogModuleCssModule {
  export interface IChangeLogModuleCss {
    change: string;
    contributors: string;
    date: string;
    message: string;
  }
}

declare const ChangeLogModuleCssModule: ChangeLogModuleCssModule.IChangeLogModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChangeLogModuleCssModule.IChangeLogModuleCss;
};

export = ChangeLogModuleCssModule;
