// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ChangeLogModuleCssNamespace {
  export interface IChangeLogModuleCss {
    change: string;
    contributors: string;
    date: string;
    message: string;
  }
}

declare const ChangeLogModuleCssModule: ChangeLogModuleCssNamespace.IChangeLogModuleCss;

export = ChangeLogModuleCssModule;
