// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace TimelineModuleCssNamespace {
  export interface ITimelineModuleCss {
    axisTick: string;
    borderColour: string;
    borderWidth: string;
    branchLabelWidth: string;
    collapsed: string;
    content: string;
    defaultRowHeight: string;
    first: string;
    gridLine: string;
    gridLineColour: string;
    item: string;
    label: string;
    major: string;
    majorGridLineColour: string;
    minimised: string;
    themeBackground: string;
    timeline: string;
    tooltip: string;
    tooltipContainer: string;
    tooltipDetails: string;
    tooltipMarker: string;
    track: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssNamespace.ITimelineModuleCss;

export = TimelineModuleCssModule;
