// This file is automatically generated. Do not edit.
declare namespace TimelineModuleCssNamespace {
  export interface ITimelineModuleCss {
    axisTick: string;
    borderColour: string;
    borderWidth: string;
    branchLabelWidth: string;
    collapsed: string;
    content: string;
    defaultRowHeight: string;
    first: string;
    gridLine: string;
    gridLineColour: string;
    item: string;
    label: string;
    major: string;
    majorGridLineColour: string;
    minimised: string;
    timeline: string;
    track: string;
  }
}

declare const TimelineModuleCssModule: TimelineModuleCssNamespace.ITimelineModuleCss;

export = TimelineModuleCssModule;
