// This file is automatically generated. Do not edit.
export const jobIcon: string;
export const cardActionTable: string;
export const cardActionRow: string;
export const buffIcon: string;
export const spreadSlot3: string;
export const buffDummy: string;
export const buffUnknown: string;
