import {DISPLAY_ORDER as CORE_ORDER} from 'parser/core/modules/DISPLAY_ORDER'

export const DISPLAY_ORDER = {
	DOT_CHECKLIST: 2,
	DIVINATION_CHECKLIST: 3,
	DRAW_CHECKLIST: 4,
	CROWN_PLAY_CHECKLIST: 5,
	HEALING_OGCDS_CHECKLIST: 6,
	OVERHEAL_CHECKLIST: 7,
	DIVINATION: 53,
	ARCANA_TRACKING: 55,
	DROPPED_DEFENSIVES: CORE_ORDER.DEFENSIVES + 1,
	UTILITIES: CORE_ORDER.DEFENSIVES + 2,
}
