import DISPLAY_ORDER from 'parser/core/modules/DISPLAY_ORDER'

export default {
	DOT_CHECKLIST: 2,
	DIVINATION_CHECKLIST: 3,
	DRAW_CHECKLIST: 4,
	CROWN_PLAY_CHECKLIST: 5,
	HEALING_OGCDS_CHECKLIST: 6,
	OVERHEAL_CHECKLIST: 7,
	DIVINATION: 53,
	ARCANA_TRACKING: 55,
	DROPPED_DEFENSIVES: DISPLAY_ORDER.DEFENSIVES + 1,
}
