// This file is automatically generated. Do not edit.
declare namespace MessageModuleCssModule {
  export interface IMessageModuleCss {
    backgroundLightness: string;
    block: string;
    colorLightness: string;
    error: string;
    gutter: string;
    header: string;
    icon: string;
    info: string;
    message: string;
    success: string;
    themeBlue: string;
    themeGreen: string;
    themeGrey: string;
    themeRed: string;
    themeYellow: string;
    warning: string;
  }
}

declare const MessageModuleCssModule: MessageModuleCssModule.IMessageModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessageModuleCssModule.IMessageModuleCss;
};

export = MessageModuleCssModule;
