// This file is automatically generated. Do not edit.
declare namespace MessageModuleCssModule {
  export interface IMessageModuleCss {
    block: string;
    box: string;
    default: string;
    error: string;
    errorBackground: string;
    errorText: string;
    gutter: string;
    header: string;
    icon: string;
    info: string;
    infoBackground: string;
    infoText: string;
    message: string;
    messageBackground: string;
    messageText: string;
    success: string;
    successBackground: string;
    successText: string;
    text: string;
    warning: string;
    warningBackground: string;
    warningText: string;
  }
}

declare const MessageModuleCssModule: MessageModuleCssModule.IMessageModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessageModuleCssModule.IMessageModuleCss;
};

export = MessageModuleCssModule;
