// This file is automatically generated. Do not edit.
export interface IMessageModuleCss {
  backgroundLightness: string;
  block: string;
  colorLightness: string;
  error: string;
  gutter: string;
  header: string;
  icon: string;
  info: string;
  message: string;
  success: string;
  themeBlue: string;
  themeGreen: string;
  themeGrey: string;
  themeRed: string;
  themeYellow: string;
  warning: string;
}

export const locals: IMessageModuleCss;
export default locals;
