// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ProcOverlayModuleCssNamespace {
  export interface IProcOverlayModuleCss {
    link: string;
    procOverlay: string;
  }
}

declare const ProcOverlayModuleCssModule: ProcOverlayModuleCssNamespace.IProcOverlayModuleCss;

export = ProcOverlayModuleCssModule;
