// This file is automatically generated. Do not edit.
declare namespace ThemeModuleCssNamespace {
  export interface IThemeModuleCss {
    backgroundLightness: string;
    colorLightness: string;
    darkMode: string;
    errorBackground: string;
    errorDark: string;
    errorLight: string;
    errorText: string;
    gutter: string;
    highlight: string;
    infoBackground: string;
    infoDark: string;
    infoLight: string;
    infoText: string;
    lg: string;
    md: string;
    messageBackground: string;
    messageDark: string;
    messageLight: string;
    messageText: string;
    segmentLinkActive: string;
    sm: string;
    successBackground: string;
    successDark: string;
    successLight: string;
    successText: string;
    themeBackdrop: string;
    themeBackground: string;
    themeBlack: string;
    themeBlue: string;
    themeBorder: string;
    themeBrown: string;
    themeGreen: string;
    themeGrey: string;
    themeInverse: string;
    themeLight: string;
    themeOlive: string;
    themeOrange: string;
    themePink: string;
    themePurple: string;
    themeRed: string;
    themeTeal: string;
    themeText: string;
    themeTextMuted: string;
    themeViolet: string;
    themeWhite: string;
    themeYellow: string;
    warningBackground: string;
    warningDark: string;
    warningLight: string;
    warningText: string;
    xl: string;
  }
}

declare const ThemeModuleCssModule: ThemeModuleCssNamespace.IThemeModuleCss;

export = ThemeModuleCssModule;
