// This file is automatically generated. Do not edit.
export const gutter: string;
export const sm: string;
export const md: string;
export const lg: string;
export const xl: string;
export const themeBlack: string;
export const themeLight: string;
export const themeWhite: string;
export const themeText: string;
export const themeBackground: string;
export const themeBackdrop: string;
export const themeInverse: string;
