// This file is automatically generated. Do not edit.
declare namespace MenuModuleCssModule {
  export interface IMenuModuleCss {
    bottom: string;
    gutter: string;
    item: string;
    menu: string;
    themeBackdrop: string;
    themeBackground: string;
    themeBorder: string;
    themeText: string;
    top: string;
  }
}

declare const MenuModuleCssModule: MenuModuleCssModule.IMenuModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MenuModuleCssModule.IMenuModuleCss;
};

export = MenuModuleCssModule;
