// This file is automatically generated. Do not edit.
declare namespace ActorListModuleCssModule {
  export interface IActorListModuleCss {
    group: string;
    gutter: string;
    themeBackground: string;
  }
}

declare const ActorListModuleCssModule: ActorListModuleCssModule.IActorListModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ActorListModuleCssModule.IActorListModuleCss;
};

export = ActorListModuleCssModule;
