// This file is automatically generated. Do not edit.
declare namespace PullListModuleCssModule {
  export interface IPullListModuleCss {
    banner: string;
    duration: string;
    group: string;
    groupHeader: string;
    gutter: string;
    link: string;
    links: string;
    messageBackground: string;
    progress: string;
    progressBar: string;
    segmentLinkActive: string;
    success: string;
    text: string;
    themeBackground: string;
    themeGreen: string;
    themeRed: string;
  }
}

declare const PullListModuleCssModule: PullListModuleCssModule.IPullListModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PullListModuleCssModule.IPullListModuleCss;
};

export = PullListModuleCssModule;
