// This file is automatically generated. Do not edit.
declare namespace ReportFlowModuleCssModule {
  export interface IReportFlowModuleCss {
    actorList: string;
    banner: string;
    controls: string;
    group: string;
    groupHeader: string;
    gutter: string;
    link: string;
    links: string;
    messageBackground: string;
    meta: string;
    progress: string;
    progressBar: string;
    pullList: string;
    refresh: string;
    segmentLinkActive: string;
    success: string;
    text: string;
    themeBackground: string;
    themeGreen: string;
    themeRed: string;
  }
}

declare const ReportFlowModuleCssModule: ReportFlowModuleCssModule.IReportFlowModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ReportFlowModuleCssModule.IReportFlowModuleCss;
};

export = ReportFlowModuleCssModule;
