// This file is automatically generated. Do not edit.
declare namespace ReportFlowModuleCssNamespace {
  export interface IReportFlowModuleCss {
    actorList: string;
    banner: string;
    block: string;
    controls: string;
    group: string;
    groupHeader: string;
    gutter: string;
    icon: string;
    link: string;
    links: string;
    messageBackground: string;
    meta: string;
    progress: string;
    progressBar: string;
    pullList: string;
    refresh: string;
    reportLink: string;
    segmentLinkActive: string;
    success: string;
    text: string;
    themeBackground: string;
    themeGreen: string;
    themeRed: string;
    themeText: string;
  }
}

declare const ReportFlowModuleCssModule: ReportFlowModuleCssNamespace.IReportFlowModuleCss;

export = ReportFlowModuleCssModule;
