// This file is automatically generated. Do not edit.
declare namespace SegmentModuleCssNamespace {
  export interface ISegmentModuleCss {
    block: string;
    expand: string;
    expandMarker: string;
    expandable: string;
    gutter: string;
    segment: string;
    themeBackground: string;
    transitionDuration: string;
  }
}

declare const SegmentModuleCssModule: SegmentModuleCssNamespace.ISegmentModuleCss;

export = SegmentModuleCssModule;
