// This file is automatically generated. Do not edit.
export const gutter: string;
export const themeBackground: string;
export const block: string;
export const transitionDuration: string;
export const segment: string;
export const expandable: string;
export const expand: string;
export const expandMarker: string;
