// This file is automatically generated. Do not edit.
declare namespace SegmentModuleCssModule {
  export interface ISegmentModuleCss {
    block: string;
    expand: string;
    expandMarker: string;
    expandable: string;
    gutter: string;
    segment: string;
    themeBackground: string;
    transitionDuration: string;
  }
}

declare const SegmentModuleCssModule: SegmentModuleCssModule.ISegmentModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SegmentModuleCssModule.ISegmentModuleCss;
};

export = SegmentModuleCssModule;
