name: Build
on:
  pull_request: {}
  # TODO: need a push here too

permissions:
  checks: write

jobs:
  gate:
    if: github.repository_owner == 'xivanalysis'
    runs-on: ubuntu-latest
    steps:
    - run: echo "running on upstream repository"

  lint:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    - run: yarn lint --format=compact

  typecheck:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    - run: yarn types

  check-extract:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    - run: bash ./.github/scripts/check-extract.sh

  test:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    # TODO: swap this to `--reporters=github-actions` and remove this
    # package once jest is targeting >28
    - run: yarn test --reporters=jest-github-actions-reporter

  checks-pass:
    runs-on: ubuntu-latest
    needs:
    - lint
    - typecheck
    - check-extract
    - test
    steps:
    - run: echo "all checks passing"

  # TODO: ok everything from this point on should only execute for actual merges
  build:
    runs-on: ubuntu-latest
    needs: [checks-pass]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    # Build
    - name: build
      run: |
        yarn extract
        export REACT_APP_VERSION=$GITHUB_RUN_NUMBER
        export REACT_APP_GIT_COMMIT=$(git rev-parse --short HEAD)
        export REACT_APP_GIT_BRANCH=$GITHUB_REF_NAME
        CI=false NODE_ENV=production yarn build
    - uses: actions/upload-artifact@v4
      with:
        name: dist-client
        path: build
        retention-days: 7
  
  # This is seperated out such that it can be re-run seperately to the rest of the build.
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    # Ensure that only one build can deploy at a time.
    concurrency: production
    environment: aposimz
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist-client
        path: build
    - name: set environment
      run: |
        BUILD_ID="${{ github.ref_name }}.${{ github.sha }}"
        echo "BUILD_ID=${BUILD_ID/\//_}" >> "$GITHUB_ENV"
        if [ ${{ github.event_name}} == "push" ]; then
          echo "COMPARE=${{ github.event.before }}...${{ github.event.after }}" >> "$GITHUB_ENV"
        else
          echo "COMPARE=${{ github.sha }}^...${{ github.sha }}" >> "$GITHUB_ENV"
        fi
    - name: prepare payload
      run: |
        mv build $BUILD_ID
        tar -czf $BUILD_ID.tgz $BUILD_ID
    - name: connect to tailnet
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:xivanalysis
    - name: upload
      run: scp -q -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $BUILD_ID.tgz ${{ secrets.DEPLOY_SSH_REMOTE }}:${{ secrets.DEPLOY_CLIENT_PATH }}/deploy-cache
    - name: deploy
      run: ssh -q -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DEPLOY_SSH_REMOTE }} "cd ${{ secrets.DEPLOY_CLIENT_PATH }} && ./deploy.sh ${GITHUB_REF_NAME/\//_} ${{ github.sha }}"
    - name: success webhook
      run: bash ./.github/scripts/success.sh
    - name: failure webhook
      if: failure()
      run: bash ./.github/scripts/fail.sh

    # TODO: work out how to send a deploy notification
    # possibly can use https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-with-github-actions in combo with standard gh webhook? not sure. could always just use the existing scripts too
