name: Build
on:
  pull_request: {}
  # TODO: need a push here too

permissions:
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # TODO: does this work on PRs? one way to find out!
    if: github.repository_owner == 'xivanalysis'

    steps:
    # Set up the repository & node environment
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
    - run: yarn install
    # Run lints
    # TODO: swap this to `--reporters=github-actions` and remove this
    # package once jest is targeting >28
    - run: yarn lint --reporters=jest-github-actions-reporter
    - run: yarn types
    - run: bash ./.github/scripts/check-extract.sh
