name: checks
on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request: {}

jobs:
  gate:
    if: github.repository_owner == 'xivanalysis'
    runs-on: ubuntu-latest
    steps:
    - run: echo "running on upstream repository"

  lint:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [gate]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare-workspace
    - run: yarn test

  checks-pass:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps:
    - run: echo "all checks passing"
