name: Danger
on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}
