name: Labeler
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.repository == 'xivanalysis/xivanalysis'
    steps:
      - uses: paulfantom/periodic-labeler@3bafde5d1fb46a2574044baf4070471f6d6a7df9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
