// This file is automatically generated. Do not edit.
declare namespace DbLinkModuleCssNamespace {
  export interface IDbLinkModuleCss {
    image: string;
    link: string;
  }
}

declare const DbLinkModuleCssModule: DbLinkModuleCssNamespace.IDbLinkModuleCss;

export = DbLinkModuleCssModule;
