// This file is automatically generated. Do not edit.
declare namespace DbLinkModuleCssModule {
  export interface IDbLinkModuleCss {
    image: string;
    link: string;
  }
}

declare const DbLinkModuleCssModule: DbLinkModuleCssModule.IDbLinkModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: DbLinkModuleCssModule.IDbLinkModuleCss;
};

export = DbLinkModuleCssModule;
