// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace DbLinkModuleCssNamespace {
  export interface IDbLinkModuleCss {
    detail: string;
    image: string;
    link: string;
  }
}

declare const DbLinkModuleCssModule: DbLinkModuleCssNamespace.IDbLinkModuleCss;

export = DbLinkModuleCssModule;
