// This file is automatically generated. Do not edit.
declare namespace GlossaryTermModuleCssModule {
  export interface IGlossaryTermModuleCss {
    term: string;
  }
}

declare const GlossaryTermModuleCssModule: GlossaryTermModuleCssModule.IGlossaryTermModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlossaryTermModuleCssModule.IGlossaryTermModuleCss;
};

export = GlossaryTermModuleCssModule;
