// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace GlossaryTermModuleCssNamespace {
  export interface IGlossaryTermModuleCss {
    term: string;
  }
}

declare const GlossaryTermModuleCssModule: GlossaryTermModuleCssNamespace.IGlossaryTermModuleCss;

export = GlossaryTermModuleCssModule;
