// This file is automatically generated. Do not edit.
declare namespace I18NMenuModuleCssNamespace {
  export interface II18NMenuModuleCss {
    container: string;
    crowdinLogo: string;
    dropdown: string;
    menuItem: string;
  }
}

declare const I18NMenuModuleCssModule: I18NMenuModuleCssNamespace.II18NMenuModuleCss;

export = I18NMenuModuleCssModule;
