// This file is automatically generated. Do not edit.
declare namespace I18NMenuModuleCssModule {
  export interface II18NMenuModuleCss {
    container: string;
    crowdinLogo: string;
    dropdown: string;
    menuItem: string;
  }
}

declare const I18NMenuModuleCssModule: I18NMenuModuleCssModule.II18NMenuModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: I18NMenuModuleCssModule.II18NMenuModuleCss;
};

export = I18NMenuModuleCssModule;
