// This file is automatically generated. Do not edit.
export interface II18nMenuModuleCss {
  container: string;
  crowdinLogo: string;
  dropdown: string;
  menuItem: string;
}

export const locals: II18nMenuModuleCss;
export default locals;
