// This file is automatically generated. Do not edit.
export interface IRotationModuleCss {
  container: string;
  gcdSize: string;
  link: string;
  ogcd: string;
  ogcdSize: string;
}

export const locals: IRotationModuleCss;
export default locals;
