// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace RotationModuleCssNamespace {
  export interface IRotationModuleCss {
    container: string;
    gcdSize: string;
    ghostOverlay: string;
    link: string;
    ogcd: string;
    ogcdSize: string;
  }
}

declare const RotationModuleCssModule: RotationModuleCssNamespace.IRotationModuleCss;

export = RotationModuleCssModule;
