// This file is automatically generated. Do not edit.
/* eslint-disable */
declare namespace ThemeMenuModuleCssNamespace {
  export interface IThemeMenuModuleCss {
    container: string;
    crowdinLogo: string;
    dropdown: string;
    menuItem: string;
  }
}

declare const ThemeMenuModuleCssModule: ThemeMenuModuleCssNamespace.IThemeMenuModuleCss;

export = ThemeMenuModuleCssModule;
