// This file is automatically generated. Do not edit.
declare namespace DualStatisticModuleCssModule {
  export interface IDualStatisticModuleCss {
    dualStatistic: string;
    gutter: string;
    icon: string;
    title: string;
    titleWrapper: string;
    value: string;
  }
}

declare const DualStatisticModuleCssModule: DualStatisticModuleCssModule.IDualStatisticModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: DualStatisticModuleCssModule.IDualStatisticModuleCss;
};

export = DualStatisticModuleCssModule;
