// This file is automatically generated. Do not edit.
export interface IDualStatisticModuleCss {
  dualStatistic: string;
  gutter: string;
  icon: string;
  title: string;
  titleWrapper: string;
  value: string;
}

export const locals: IDualStatisticModuleCss;
export default locals;
