// This file is automatically generated. Do not edit.
declare namespace DualStatisticModuleCssNamespace {
  export interface IDualStatisticModuleCss {
    dualStatistic: string;
    gutter: string;
    icon: string;
    title: string;
    titleWrapper: string;
    value: string;
  }
}

declare const DualStatisticModuleCssModule: DualStatisticModuleCssNamespace.IDualStatisticModuleCss;

export = DualStatisticModuleCssModule;
