// This file is automatically generated. Do not edit.
declare namespace CombatantListModuleCssModule {
  export interface ICombatantListModuleCss {
    friendLink: string;
    supportedPatches: string;
    themeText: string;
  }
}

declare const CombatantListModuleCssModule: CombatantListModuleCssModule.ICombatantListModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CombatantListModuleCssModule.ICombatantListModuleCss;
};

export = CombatantListModuleCssModule;
