// This file is automatically generated. Do not edit.
export interface ICombatantListModuleCss {
  friendLink: string;
  supportedPatches: string;
  themeText: string;
}

export const locals: ICombatantListModuleCss;
export default locals;
