// This file is automatically generated. Do not edit.
declare namespace FightItemModuleCssModule {
  export interface IFightItemModuleCss {
    progress: string;
  }
}

declare const FightItemModuleCssModule: FightItemModuleCssModule.IFightItemModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FightItemModuleCssModule.IFightItemModuleCss;
};

export = FightItemModuleCssModule;
