// This file is automatically generated. Do not edit.
export const gutter: string;
export const md: string;
export const fightList: string;
export const refresh: string;
export const groupHeader: string;
export const groupHeaderBackground: string;
