// This file is automatically generated. Do not edit.
export interface IFightListModuleCss {
  fightList: string;
  groupHeader: string;
  groupHeaderBackground: string;
  gutter: string;
  md: string;
  refresh: string;
}

export const locals: IFightListModuleCss;
export default locals;
