// This file is automatically generated. Do not edit.
declare namespace FightListModuleCssModule {
  export interface IFightListModuleCss {
    fightList: string;
    groupHeader: string;
    groupHeaderBackground: string;
    gutter: string;
    md: string;
    refresh: string;
  }
}

declare const FightListModuleCssModule: FightListModuleCssModule.IFightListModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FightListModuleCssModule.IFightListModuleCss;
};

export = FightListModuleCssModule;
