// This file is automatically generated. Do not edit.
/* eslint-disable */
export const gutter: string;
export const themeBackground: string;
export const verticalSpacing: string;
export const block: string;
